# Generated by Django 5.1.2 on 2024-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='flag',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
