# Generated by Django 5.1.2 on 2024-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_job_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_c_id',
            field=models.IntegerField(default=-1),
        ),
    ]
