# Generated by Django 5.1.2 on 2024-11-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_job_job_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_c_id',
        ),
    ]
